Added delay to IMU reset
purduesigbots/pros pull request #286
Opened 2021-04-19 21:11 UTC by belericant

#### Summary:
The calibration flag is not set immediately after a call to `imu_reset` necessitating user code to add a delay before polling the status of the IMU. By adding a 20 ms delay after calling `vexDeviceImuReset` in `imu_reset`, the calibration flag is correctly set once the function returns.

#### Motivation:
`imu_get_status` should reflect that the IMU is calibrating immediately upon the return of `imu_reset`.

#### Test Plan:
- [ ] find the delay necessary for the calibration flag to be set
- [ ] make sure `imu_reset` and `get_status` still work

The delay between `vexDeviceImuReset` and the calibration flag being set was found by running 

```c
void initialize() {
  imu_reset(IMU_PORT);
  uint32_t start_time = millis();
  while (!(imu_get_status(IMU_PORT) & E_IMU_STATUS_CALIBRATING)) {

  }
  uint32_t delta = millis() - start_time;

  FILE* file = fopen("/usd/logging.csv", "a");
  char str[100];
  sprintf(str, "%d, ", delta);
  fputs(str, file);
  fclose(file);
}
```

The resulting log file after running the program 100 times showed that the delay was a consistent 12 ms.

2021-04-19 21:21 UTC, Buzzec commented
The current [documentation](https://github.com/purduesigbots/pros/blob/866cfefcf7b089ca28e9e0bdfcb14cd126ecbe42/include/pros/imu.h#L61) for `imu_reset` states 
```
This takes approximately 2 seconds, and is a non-blocking operation.
```
This change would make this a blocking operation so the documentation needs to be changed to reflect the new behavior. I think the documentation is enough already and is user error if they don't put a delay before using the imu after a reset.

2021-04-19 21:25 UTC, belericant commented
The change to `imu_reset` isn't meant to block for the entirety of calibration. The current example for the documentation is:
```c
#define IMU_PORT 1

void initialize() {
  imu_reset(IMU_PORT);
  int time = millis();
  int iter = 0;
  while (imu_get_status(IMU_PORT) & E_IMU_STATUS_CALIBRATING) {
    printf("IMU calibrating... %d\n", iter);
    iter += 10;
    delay(10);
  }
  // should print about 2000 ms
  printf("IMU is done calibrating (took %d ms)\n", iter - time);
}
```
This does not work currently because on the return of `imu_reset` a subsequent call to `imu_get_status` will still show the IMU as done calibrating which is not user error as the expected behavior after `imu_reset` is that the IMU status return that the IMU is calibrating.

2021-06-15 15:02 UTC, kunwarsahni01 commented
/azp run

2021-06-17 17:50 UTC, WillXuCodes requested changes
Given that the 12 ms delay could change depending on the amount of motors attached, I recommend a more variable approach:

`
while(!(vexDeviceImuStatusGet(device->device_info) & E_IMU_STATUS_CALIBRATING)) delay(1);
`

2021-06-17 17:53 UTC, HotelCalifornia commented
> Given that the 12 ms delay could change depending on the amount of motors attached, I recommend a more variable approach:
> 
> `while(!(vexDeviceImuStatusGet(device->device_info) & E_IMU_STATUS_CALIBRATING)) delay(1);`

this fundamentally changes the nature of the calibration function from nonblocking to blocking. as discussed above, the point of this change is to allow the system time for the calibrating status flag to update so that users can query status as we recommend in the documentation, NOT to block for the entirety of calibration.

2021-06-17 18:04 UTC, WillXuCodes commented
> > Given that the 12 ms delay could change depending on the amount of motors attached, I recommend a more variable approach:
> > `while(!(vexDeviceImuStatusGet(device->device_info) & E_IMU_STATUS_CALIBRATING)) delay(1);`
> 
> this fundamentally changes the nature of the calibration function from nonblocking to blocking. as discussed above, the point of this change is to allow the system time for the calibrating status flag to update so that users can query status as we recommend in the documentation, NOT to block for the entirety of calibration.

Right, hence the **!**(vexDeviceImuStatusGet(device->device_info) & E_IMU_STATUS_CALIBRATING) is intended to wait until the calibrating status flag has been updated properly before exiting the function scope. If we wanted to block the entirety of calibration, the **not** would not be there.

2021-06-17 18:14 UTC, nathan-moore commented
@belericant in what cases are you calling imu reset? Is that use case covered by the tare functions?

2021-06-20 06:05 UTC, belericant commented
> @belericant in what cases are you calling imu reset baring doing it initially? Is that use case covered by the tare functions?

I think most use cases of reset are only in the init portion of the program. It's just the reset function can cause many issues later on since code that waits on the IMU to be calibrated runs prematurely and many users don't figure this out because the example in the docs has this very issue and is assumed to be correct.



> > > Given that the 12 ms delay could change depending on the amount of motors attached, I recommend a more variable approach:
> > > `while(!(vexDeviceImuStatusGet(device->device_info) & E_IMU_STATUS_CALIBRATING)) delay(5);`
> > 
> > 
> > this fundamentally changes the nature of the calibration function from nonblocking to blocking. as discussed above, the point of this change is to allow the system time for the calibrating status flag to update so that users can query status as we recommend in the documentation, NOT to block for the entirety of calibration.
> 
> Right, hence the **!**(vexDeviceImuStatusGet(device->device_info) & E_IMU_STATUS_CALIBRATING) is intended to wait until the calibrating status flag has been updated properly before exiting the function scope. If we wanted to block the entirety of calibration, the **not** would not be there.

This is probably the more elegant solution. I just stuck with one delay because I found in testing that the time needed between reset being called and the flag being updated was consistent across all runs.

2021-06-20 06:20 UTC, WillXuCodes commented
Neat, well the sooner you can make the suggested changes and all that, we will test and see if the change works with your test code.

2021-06-21 15:58 UTC, WillXuCodes requested changes
Could you make the delay 5 ms? As well as update the non-blocking comment in the function header.

2021-06-21 20:05 UTC, belericant commented
> Could you make the delay 5 ms? As well as update the non-blocking comment in the function header.

Which comment are you referring to?

2021-06-21 20:11 UTC, WillXuCodes commented
> > Could you make the delay 5 ms? As well as update the non-blocking comment in the function header.
> 
> Which comment are you referring to?

https://github.com/purduesigbots/pros/blob/develop/include/pros/imu.h#L64 

and the respective commend in the hpp file. (Maybe say something such as "and is a blocking operation until the IMU status flag is set properly."

2021-07-01 22:25 UTC, WillXuCodes commented
![image](https://user-images.githubusercontent.com/54247087/124196053-3dfc7380-da91-11eb-965b-e2fde48b3c17.png)
Just tested the PR, the delay works. However, it must be noted that I had to add a short delay before running reset or the entire program would hang. This is however **irrelevant** to this PR due to it being a known issue that happens on every V5 coding environment.

2021-07-01 22:26 UTC, WillXuCodes approved these changes

2021-07-01 22:26 UTC, WillXuCodes commented
With testing done and showing similar values to @belericant's testing, this PR looks good to me!

2021-07-01 22:27 UTC, merged