Create alias pros::Imu for pros::IMU in IMU.h and IMU.hpp
purduesigbots/pros pull request #293
Opened 2021-05-16 23:02 UTC by AyushShukla3

#### Summary:
Create the pros::Imu alias for pros::IMU in imu.h and imu.hpp

#### Motivation:
Reduce confusion with newer users attempting to use pros::Imu instead of pros;:IMU

##### References (optional):
issue#288

2021-05-16 23:39 UTC, HotelCalifornia requested changes

2021-05-16 23:39 UTC, HotelCalifornia commented on include/api.h
> +#define PROS_VERSION_STRING "3.3.2-dirty.10.5abe157"
Don't check this file into features or bugfixes

2021-05-16 23:39 UTC, HotelCalifornia commented on include/pros/imu.h
> +typedef struct IMU Imu;
does this even compile? there are no such structs defined in the C API. I think it is sufficient to provide that alias for the C++ API only.

2021-05-16 23:39 UTC, HotelCalifornia commented on version
> +3.3.2-dirty.10.5abe157
this file should also not be checked into changes like this

2021-05-16 23:40 UTC, HotelCalifornia commented
also if you edit the description above to say "closes #288" it will automatically close that issue when this is merged

2021-05-17 16:59 UTC, WillXuCodes requested changes
Newline on Version

2021-05-17 17:01 UTC, HotelCalifornia commented on include/pros/imu.hpp
> +	using IMU = Imu;
should not be indented here

2021-05-17 17:01 UTC, WillXuCodes submitted a review, later dismissed
LGTM

2021-05-17 17:03 UTC, HotelCalifornia approved these changes

2021-05-17 17:06 UTC, merged