✨Implement Error Handling For Screen
purduesigbots/pros pull request #344
Opened 2022-01-21 04:57 UTC by AurinDutta

#### Summary:
Implemented error catching and handling for the screen class, where if an error is detected (e.g. a mutex isn't able to be taken), the method in question will catch the error, set errno to the proper error, and return PROS_ERR. 

#### Motivation:
The screen class didn't have any error catching or handling, as such this addition will help users when debugging their code.

##### References (optional):
closes #328 

#### Test Plan:
While a mutex is taken, run methods from the screen class; if they set errno correctly and return PROS_ERR, then the error handling works fine.

- [ ] test item

2022-01-21 05:02 UTC, HotelCalifornia reviewed
some nitpicks with doc comments

2022-01-21 05:02 UTC, HotelCalifornia commented on include/pros/screen.h
> + * \return Returns 1 if the mutex was successfully returned, or prosERR if there was an error either taking or
PROS_ERR not prosERR (here and throughout the file)

2022-01-21 05:02 UTC, HotelCalifornia commented on include/pros/screen.h
> + * \return 1 if there were no errors, or PROS_ERR if an error occured taking or returning the screen mutex.
Make sure your comments aren't going past column 80 on any line

2022-01-21 06:42 UTC, WillXuCodes requested changes

2022-01-21 06:42 UTC, WillXuCodes commented on include/pros/screen.h
> +    MUTEX_ERROR // An error occured while taking/returning the mutex
Also change it to E_TOUCH_ERROR or something more in line with the other enum options.

2022-01-21 06:42 UTC, WillXuCodes commented on src/devices/screen.c
> +uint32_t _touch_handle_task(void* ignore) {
Given that this is a daemon for handling touch callbacks, I don't think we really need this to be changed to have a return value.

2022-01-31 23:25 UTC, WillXuCodes submitted a review, later dismissed
LGTM

2022-01-31 23:33 UTC, WillXuCodes approved these changes
Thanks for fixing the comment, looks good.

2022-01-31 23:34 UTC, merged