Feature/changebgcolor
purduesigbots/pros pull request #346
Opened 2022-01-28 19:46 UTC by omegaStag

#### Summary:
Added function to change the LCD background color (takes in ``lv_color_t`` type) and an overload for the function on the C++ level (takes in both ``lv_color_t``, and three ``uint8_t`` values representing RGB values).

#### Motivation:
So that users can change the LCD background color.

##### References (optional):
closes #343 

#### Test Plan:
Use function and see if it works to change the background color.

2022-01-28 20:56 UTC, WillXuCodes requested changes

2022-01-28 20:56 UTC, WillXuCodes commented on src/display/llemu.c
> +}
Add a newline to the end of this file

2022-01-28 20:56 UTC, WillXuCodes commented on include/pros/llemu.h
> + */
Needs documentation for parameter

2022-01-28 20:56 UTC, WillXuCodes commented on include/pros/llemu.hpp
> +void set_background_color(std::uint8_t r, std::uint8_t g, std::uint8_t b);
Also needs documentation for parameter

2022-01-30 08:16 UTC, Unionjackjz1 commented
thank you <3

2022-01-31 22:43 UTC, WillXuCodes requested changes

2022-01-31 22:43 UTC, WillXuCodes commented on src/display/llemu.cpp
> +	lcd_set_background_color(lv_color_t{r,g,b,0xff});
```suggestion
	lcd_set_background_color(LV_COLOR_MAKE(r, g, b));
```

Should prob have this use the macro as well, just so the config for alpha works.

2022-01-31 22:44 UTC, WillXuCodes commented on include/pros/llemu.hpp
> + * \param r
Need proper tabbing for comments

2022-02-01 00:30 UTC, WillXuCodes approved these changes
Approved, tested with Hardware.

2022-02-02 01:31 UTC, merged