✨Add motor stop function
purduesigbots/pros pull request #348
Opened 2022-02-14 23:23 UTC by omegaStag

#### Summary:
Adds a function to set the motor voltage to zero.

#### Motivation:
There isn't already a motor stop function

##### References (optional):

#### Test Plan:
Make motor run and use function to stop motor

2022-02-21 23:40 UTC, WillXuCodes approved these changes
Looks good

2022-02-27 21:04 UTC, HotelCalifornia requested changes
I thought the point of this was to add a function that stops a motor respecting the set brake mode? as-is this PR doesn't do that. instead of internally calling move_voltage(0) it should call e.g. move_velocity(0).

also i'd recommend calling it motor_brake/pros::Motor::brake instead of motor_stop/pros::Motor::stop to make it clear that's what's happening.

2022-02-28 03:56 UTC, HotelCalifornia reviewed
some updates and clarifications I thought would be useful in the documentation

2022-02-28 03:56 UTC, HotelCalifornia commented on include/pros/motors.h
> + * Sets the velocity for the motor to 0, stopping the motor with respect to set brake mode.
```suggestion
 * Stops the motor using the currently configured brake mode.
 * 
 * This function sets motor velocity to zero, which will cause it to act
 * according to the set brake mode. If brake mode is set to MOTOR_BRAKE_HOLD,
 * this function may behave differently than calling motor_move_absolute(port, 0)
 * or motor_move_relative(port, 0).
```

2022-02-28 03:56 UTC, HotelCalifornia commented on include/pros/motors.hpp
> +	 * Sets the velocity for the motor to 0, stopping the motor with respect to set brake mode.
```suggestion
	 * Stops the motor using the currently configured brake mode.
	 *
	 * This function sets motor velocity to zero, which will cause it to act
	 * according to the set brake mode. If brake mode is set to MOTOR_BRAKE_HOLD,
	 * this function may behave differently than calling move_absolute(0)
	 * or move_relative(0).
```

2022-04-11 17:10 UTC, WillXuCodes approved these changes
Works on hardware, feel free to merge later tonight nearer to 3.6 release

2022-04-11 18:09 UTC, merged