Add getentropy to newlib stubs
purduesigbots/pros pull request #363
Opened 2022-05-18 01:04 UTC by mattfbacon

#### Summary:
Add a stub implementation of the `getentropy` function to the newlib stubs included in libpros.

#### Motivation:
Currently, if the arm-none-eabi toolchain's libc is too new, it will emit a reference to getentropy, which results in a linker error

##### References

Closes https://github.com/purduesigbots/pros/issues/362

#### Test Plan:

- [ ] Make sure that a new project with the patched libpros.a builds on Arch Linux

2022-05-18 01:04 UTC, mattfbacon commented
Unless V5 API includes a getrandom syscall (are you even allowed to tell me if it does??)

2022-05-18 01:48 UTC, WillXuCodes commented
/azp run

2022-05-18 02:27 UTC, WillXuCodes commented
[kernel@3.6.1-pr363.3463.zip](https://github.com/purduesigbots/pros/files/8712811/kernel%403.6.1-pr363.3463.zip)

This is the artifact produced, let me know if it works on your machine @mattfbacon

2022-05-18 02:30 UTC, mattfbacon commented
It works! Thanks.

2022-05-18 13:57 UTC, HotelCalifornia requested changes
other than my one comment it looks good. since this was tested and confirmed working on an arch machine we can get this merged as soon as that change is made

2022-05-18 13:57 UTC, HotelCalifornia commented on src/system/newlib_stubs.c
> +	return -1;
this should additionally set `errno = ENOSYS`

2022-05-22 05:34 UTC, WillXuCodes commented
/azp run

2022-05-22 06:32 UTC, WillXuCodes approved these changes

2022-05-22 06:33 UTC, WillXuCodes approved these changes

2022-05-22 10:43 UTC, HotelCalifornia approved these changes

2022-05-22 15:55 UTC, merged