Pros 3/feature/motor gear alias
purduesigbots/pros pull request #394
Opened 2022-07-25 10:01 UTC by aaryan-gautam

#### Summary:

Added aliases for motor gearset with color and rpm

#### Motivation:

The aliases are added in the enum motor_gearset_e and given the same value as the corresponding gearset
##### References (optional):

#Closes #387
#### Test Plan:

Run checks
- [ ] test item

2022-07-25 15:44 UTC, WillXuCodes requested changes
Requested changes made

2022-07-25 15:44 UTC, WillXuCodes commented on include/pros/motors.h
```suggestion
```
Remove newline

2022-07-25 15:44 UTC, WillXuCodes commented on include/pros/motors.h
>  #ifdef PROS_USE_SIMPLE_NAMES
Be sure to update simple names with your added enum members.

2022-07-25 15:44 UTC, WillXuCodes commented on include/pros/motors.h
> +	E_MOTOR_GEAR_600 = 2,
```suggestion
	E_MOTOR_GEARSET_36 = 0,  // 36:1, 100 RPM, Red gear set
	E_MOTOR_GEAR_RED = E_MOTOR_GEARSET_36,
	E_MOTOR_GEAR_100 = E_MOTOR_GEARSET_36,
	E_MOTOR_GEARSET_18 = 1,  // 18:1, 200 RPM, Green gear set
	E_MOTOR_GEAR_GREEN = E_MOTOR_GEARSET_18,
	E_MOTOR_GEAR_200 = E_MOTOR_GEARSET_18,
	E_MOTOR_GEARSET_06 = 2,  // 6:1, 600 RPM, Blue gear set
	E_MOTOR_GEAR_BLUE  = E_MOTOR_GEARSET_06,
	E_MOTOR_GEAR_600 = E_MOTOR_GEARSET_06,
```

makes maintenance slightly easier

2022-07-25 20:55 UTC, WillXuCodes commented
can't do it on mobile, but could you fix the title of the PR? Thanks.

2022-07-25 21:15 UTC, aaryan-gautam commented
> can't do it on mobile, but could you fix the title of the PR? Thanks.

Done

2022-07-26 04:31 UTC, WillXuCodes approved these changes
saucin

2022-07-26 04:31 UTC, merged