✨Adds Motor Groups
purduesigbots/pros pull request #400
Opened 2022-08-07 19:01 UTC by noam987

#### Summary:
Adds Motor groups to control multiple motors simultaneously.

#### Motivation:
Help foster the growth of third-party libraries by adding native support for motor groups. 

##### References (optional):
Closes #388 
#### Test Plan:
WIP

- [ ] Create a motor group
- [ ] Call each setter/move method of the motor group and compare the behavior to calling each motor individually. (More detailed Code coming soon).

2022-08-08 01:05 UTC, WillXuCodes requested changes
Will have more comments later

2022-08-08 01:05 UTC, WillXuCodes commented on include/pros/motors.hpp
> +#include "pros/rtos.hpp"
Don't think this is necessary

2022-08-10 00:44 UTC, noam987 commented on include/pros/motors.hpp
> +	}
Moved

2022-08-21 07:01 UTC, WillXuCodes requested changes

2022-08-21 07:01 UTC, WillXuCodes commented on src/devices/vdml_motors.cpp
> +#define take_motor_group_mutex_vector(error) \
claim_mg_mutex_vector(error)

2022-08-21 07:01 UTC, WillXuCodes commented on src/devices/vdml_motors.cpp
> +#define give_motor_group_mutex_vector(error) \
mg_mutex_give_vector(error)

2022-08-23 21:03 UTC, WillXuCodes requested changes
Changes requested, pls see above. (Only thing to do before 3.7.0 release)

2022-08-23 21:03 UTC, WillXuCodes commented on src/devices/vdml_motors.cpp
> +#define mg_foreach(func_call, motors)                       	\
instead of having "out" as something we expect, can we have this as a macro parameter?

2022-08-23 21:03 UTC, WillXuCodes commented on src/devices/vdml_motors.cpp
> +Motor_Group::Motor_Group(const std::initializer_list<Motor> motors) : _motors(motors), _motor_group_mutex(pros::Mutex()) {}
TODO: add constructor that allows an initializer list full of numbers, and reverse numbers if the port number is negative.

2022-08-23 21:05 UTC, WillXuCodes commented
Another thing to do is to replace all instances of "1" being returned to be PROS_SUCCESS (i've backmerged develop so it should work at this point). Another thing is that a motor group with 0 motors should be a valid motor group, so we should be returning "1" if no work is done w/ the output.

2022-08-23 21:06 UTC, WillXuCodes commented
Also, this code was tested with hardware in its current form without the requested constructors and it worked.

2022-08-25 01:42 UTC, WillXuCodes approved these changes
Hardware Tested, LGTM

2022-08-25 05:27 UTC, merged