✨Add MotorGroup alias for Motor_Group
purduesigbots/pros pull request #441
Opened 2022-10-11 02:59 UTC by evanmiller620

#### Summary:
Added one line that hopefully does what it is meant to do

#### Motivation:
Was my first project

#### Test Plan:
Try using MotorGroup and see if it functions as Motor_Group

- [ ] test item

2022-10-11 04:42 UTC, WillXuCodes requested changes

2022-10-11 04:42 UTC, WillXuCodes commented on include/pros/motors.hpp
> +	 * setting errno.Motor_Group
```suggestion
	 * setting errno.
```
accidental I presume?

2022-10-11 18:40 UTC, evanmiller620 commented on include/pros/motors.hpp
> +	 * setting errno.Motor_Group
Oops yes I'll fix that

2022-10-12 01:20 UTC, WillXuCodes approved these changes

2022-10-12 01:20 UTC, merged