✨Added functionality for size() and [] operator
purduesigbots/pros pull request #463
Opened 2022-11-10 00:43 UTC by AlexHunton2

#### Summary:
Added functionality for MotorGroups to be treated more like arrays than classes. With these changes the user should be able to index a MotorGroup similar to an array, and get its size with a size() method. This should allow MotorGroups to be looped through.

#### Motivation:
#450 

#### Test Plan:
Requires hardware testing. Asked to add this PR ASAP in order to keep ahead on schedule. Will hardware test and add information about that here when completed.

2022-11-25 09:39 UTC, WillXuCodes requested changes

2022-11-25 09:39 UTC, WillXuCodes commented on include/pros/motors.hpp
> +
Please add proper ERRNO documentation and other relevant information as seen in other comments.

2022-11-29 23:54 UTC, noam987 commented
Passed hardware testing

2022-11-29 23:55 UTC, WillXuCodes approved these changes

2022-11-29 23:56 UTC, merged