Pros4 feature/devices
purduesigbots/pros pull request #492
Opened 2023-01-20 04:06 UTC by evanmiller620

#### Summary:
Created a virtual device class with two functions: get_port() and get_type(). Which returns the port and the device type of the smart device, respectively. 

#### Motivation:
Groups functions that are in all smart devices so that they inherit from the Device class.

#### Test Plan:
Passed hardware tests:)

2023-01-25 01:44 UTC, Richard-Stump requested changes

2023-01-25 01:44 UTC, Richard-Stump commented on include/pros/distance.hpp
> +     * Returns the type of device
This is indented using spaces. Please fix to be indented with tabs instead

2023-01-25 01:44 UTC, Richard-Stump commented on include/api.h
> +#define PROS_VERSION_STRING "3.7.2-commit.96.ffd0367"
Please change the version to 3.7.3 and the version string to match

2023-02-01 00:26 UTC, WillXuCodes requested changes

2023-02-01 08:13 UTC, WillXuCodes approved these changes
everything ready to go.

2023-02-02 05:56 UTC, merged