Pros 4/bugfix/non-virtual get_type in device base class
purduesigbots/pros pull request #547
Opened 2023-03-09 02:33 UTC by aberiggs

#### Summary:
Implement the device class as a base class with get_type() no longer being a virtual function. Renamed get_type() to get_plugged_type() for clarity, as get_type() now makes a registry call to get the device type plugged into the port associated with a given Device object.

Removed get_type() from children of the device class.

Implemented changes (based on Ryan Doan's PR) to vdml.h and registry.h to define v5_device_e_t

#### Motivation:
Allows for users to dynamically find out the type of device that is plugged in.

##### References:
Closes #527 

#### Test Plan:

- [ ] Connect device to port and initialize a device object for it.
- [ ] Call get_plugged_type() on that device.
- [ ] Check that device enum is what is expected.
- [ ] Plug in different device while still running and check that device enum changes to correctly display the new connected device.

2023-03-09 23:51 UTC, Richard-Stump commented on src/devices/vdml_device.cpp
> +	std::uint8_t Device::get_port(void) {
Could you fix the indentation here? We don't indent within namespaces.

2023-03-09 23:51 UTC, Richard-Stump commented on include/vdml/vdml.h
> +#define v5_device_e_t pros::c::v5_device_e_t
This conditional define can probably get removed since we went with the `DeviceType` enum class instead of the `v5_device_e_t` enum.

2023-03-13 00:32 UTC, WillXuCodes requested changes
One other request: can we remove the include for rtos.hpp and misc.hpp and move the DeviceType enum class into device.hpp? Thanks.

2023-03-13 00:32 UTC, WillXuCodes commented on Makefile
> +# $(call test_output,$D$(OBJCOPY) -S -D -g --strip-unneeded --keep-symbols public_symbols.txt $@,$(DONE_STRING))
```suggestion
# $(call test_output,$D$(OBJCOPY) -S -D -g --strip-unneeded --keep-symbols public_symbols.txt $@,$(DONE_STRING))

```
Add newline back

2023-03-13 00:32 UTC, WillXuCodes commented on src/devices/vdml_device.cpp
> +}  // namespace p
```suggestion
}  // namespace v5
}  // namespace pros

```
Revert

2023-03-13 00:32 UTC, WillXuCodes commented on src/devices/vdml_device.cpp
> + *
lol be sure to add errno vals here

2023-03-16 03:34 UTC, WillXuCodes commented on src/devices/vdml_device.cpp
> + *
(Oh crap nevermind I am stupid... this was not necessary. I'm insanely sorry don't let me do late night code review ever again )

2023-03-16 04:09 UTC, WillXuCodes approved these changes
LGTM

2023-03-16 04:09 UTC, merged