:memo: update version of c and c++ in readme
purduesigbots/pros pull request #710
Opened 2024-10-26 00:57 UTC by SizzinSeal

simple PR, see title

2024-11-08 00:09 UTC, Rocky14683 requested changes

2024-11-08 00:09 UTC, Rocky14683 commented on README.md
> +PROS is built using the GCC toolchain and standard C/C++ practices (C2x & C++23 w/GNU extensions) to make the learning curve small. Structures, pointers, dynamic memory allocation, and function point
it should be C23

2024-11-09 02:39 UTC, SizzinSeal commented on README.md
> +PROS is built using the GCC toolchain and standard C/C++ practices (C2x & C++23 w/GNU extensions) to make the learning curve small. Structures, pointers, dynamic memory allocation, and function point
isn't the compiler flag C2X?

2024-11-19 19:33 UTC, SizzinSeal commented
@Rocky14683 ready for another review

2024-11-19 19:40 UTC, Rocky14683 approved these changes
LGTM

2024-12-18 17:12 UTC, merged