✨ Motor Type Getter
purduesigbots/pros pull request #723
Opened 2024-11-19 22:24 UTC by SizzinSeal

#### Summary:
add API that gets the type of a motor

#### Motivation:
V5 Motors and EXP Motors have slightly different behaviour. For example, EXP motors achieve their max velocity at 8v, while V5 motors achieve their max velocity at 12v. The user may wish to handle this difference, but this requires that they know the type of the motor that's currently plugged in

#### Test Plan:

- [ ] motor_get_type returns MOTOR_TYPE_V5 if a v5 motor is plugged in
- [ ] motor_get_type returns MOTOR_TYPE_EXP if an EXP motor is plugged in
- [ ] motor_get_type returns MOTOR_TYPE_INVALID if no motor is plugged in
- [ ] motor_get_type returns MOTOR_TYPE_INVALID if something other than a motor is plugged in
- [ ] above tests succeed when using Motor::get_type
- [ ] above tests succeed when using Motor::get_type_all
- [ ] above tests succeed when using MotorGroup::get_type
- [ ] above tests succeed when using MotorGroup::get_type_all

2024-11-19 22:26 UTC, Rocky14683 requested changes

2024-11-19 22:26 UTC, Rocky14683 commented on src/devices/vdml_motors.c
> +	//int32_t rtn = vexDeviceMotorTypeGet(device->device_info);
is this by accident?

2024-11-19 22:27 UTC, SizzinSeal commented on src/devices/vdml_motors.c
> +	//int32_t rtn = vexDeviceMotorTypeGet(device->device_info);
oh yea it is, one moment

2024-11-19 22:53 UTC, Rocky14683 commented
/azp run

2024-11-19 23:00 UTC, Rocky14683 commented
[Download link](https://artprodcus3.artifacts.visualstudio.com/A268c8aad-3bb0-47d2-9a57-cf06a843d2e8/a421d041-2579-4bf8-a0aa-d7a0307dade3/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3B1cmR1ZS1hY20tc2lnYm90cy9wcm9qZWN0SWQvYTQyMWQwNDEtMjU3OS00YmY4LWEwYWEtZDdhMDMwN2RhZGUzL2J1aWxkSWQvNjU5My9hcnRpZmFjdE5hbWUvdGVtcGxhdGU1/content?format=zip)

2024-12-13 19:09 UTC, Rocky14683 commented
/azp run

2024-12-13 19:12 UTC, Rocky14683 commented
[download link](https://artprodcus3.artifacts.visualstudio.com/A268c8aad-3bb0-47d2-9a57-cf06a843d2e8/a421d041-2579-4bf8-a0aa-d7a0307dade3/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3B1cmR1ZS1hY20tc2lnYm90cy9wcm9qZWN0SWQvYTQyMWQwNDEtMjU3OS00YmY4LWEwYWEtZDdhMDMwN2RhZGUzL2J1aWxkSWQvNjYyMS9hcnRpZmFjdE5hbWUvdGVtcGxhdGU1/content?format=zip)

2024-12-14 03:27 UTC, Rocky14683 approved these changes
LGTM for beta, for actual release we need to add alias for enums

2024-12-18 17:14 UTC, merged