aivision for beta release
purduesigbots/pros pull request #729
Opened 2024-12-08 22:14 UTC by Rocky14683

#### Summary:
ai vision sensor for beta release(so no docs for cpp)

2024-12-17 08:07 UTC, WillXuCodes requested changes
Minor fixes, not commenting on functionality for now because my impression is that this hasn't been hardware tested yet.

2024-12-17 08:07 UTC, WillXuCodes commented on include/api.h
> +#include "pros/aivision.h"
So I'm not really a big fan of the "aivision" name, at least make it `ai_vision` or `ai_camera` (underscore matters the most, vision might be a little to ambigious)?

2024-12-17 08:07 UTC, WillXuCodes commented on include/pros/aivision.hpp
> +enum class AivisionDetectType : uint8_t { color = (1 << 0), code = (1 << 1), object = (1 << 2), tag = (1 << 3) };
be nice to have this on seperate lines for readability's sake:
```suggestion
enum class AivisionDetectType : uint8_t { 
    color = (1 << 0), 
    code = (1 << 1), 
    object = (1 << 2),
    tag = (1 << 3) 
};
```

2024-12-17 08:07 UTC, WillXuCodes commented on include/api.h
> +#include "pros/aivision.h"
(actually vision is fine but I'd prefer a underscore between ai and vision just for readability's sake)

2024-12-17 08:07 UTC, WillXuCodes commented on src/devices/vdml_aivision.c
> +	  return_port(port - 1, enabled_detection_types);
```suggestion
    claim_port_i(port - 1, E_DEVICE_AIVISION);
    uint8_t enabled_detection_types = vexDeviceAiVisionEnableGet(device->device_info);
    return_port(port - 1, enabled_detection_types);
```
Inconsistent spacing

2024-12-17 08:07 UTC, WillXuCodes commented on src/devices/vdml_aivision.c
> +	  vexDeviceAiVisionClassNameGet(device->device_info, id, class_name);
Same thing here, it's a spaces vs tabs issue (we have a formatter on kernel right?)

2024-12-17 08:07 UTC, WillXuCodes commented on src/devices/vdml_aivision.cpp
> +}
Missing newline

2025-01-14 21:12 UTC, AndrewLuGit approved these changes
LGTM

2025-01-15 16:08 UTC, Rocky14683 commented
/azp run

2025-01-16 00:07 UTC, merged